ViewModels/CreateRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Asp.netCore_MVC.ViewModels
{
    public class CreateRoleViewModel
    {
        #region Properties

        [Required(ErrorMessage = "Please Enter Role Name")]
        public string? RoleName { get; set; }
        #endregion
    }
}

ViewModels/EditRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Asp.netCore_MVC.ViewModels
{
    public class EditRoleViewModel
    {
        #region Constructor

        public EditRoleViewModel()
        {
            this.Users = new List<string>();
        }
        #endregion

        #region Properties

        public string? Id { get; set; }

        [Required(ErrorMessage = "Role Name is required")]
        public string? RoleName { get; set; }

        public IList<string> Users { get; set; }
        #endregion
    }
}

ViewModels/EditUserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Asp.netCore_MVC.ViewModels
{
    public class EditUserViewModel
    {

        #region Constructor

        public EditUserViewModel()
        {
            this.Claims = new List<string>();
            this.Roles = new List<string>();
        }
        #endregion

        #region Properties

        public string? Id { get; set; }

        [Required]
        public string? UserName { get; set; }

        [Required]
        [EmailAddress]
        public string? Email { get; set; }

        public string City { get; set; }

        public List<string> Claims { get; set; }

        public List<string> Roles { get; set; }

        #endregion
    }
}

Controllers/AdministrationController.cs
using Asp.netCore_MVC.Models;
using Asp.netCore_MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Security.Claims;


namespace Asp.netCore_MVC.Controllers
{
    //[Authorize(Policy = "AdminRolePolicy")]
    public class AdministrationController : Controller
    {
        #region Properties

        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ILogger<AdministrationController> logger;
        #endregion

        #region Constructor

        public AdministrationController(RoleManager<IdentityRole> roleManager,
            UserManager<ApplicationUser> userManager,
            ILogger<AdministrationController> logger)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.logger = logger;
        }
        #endregion

        #region CreateRole

        /// <summary>
        /// Create Role View
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult CreateRole()
        {
            return this.View();
        }

        /// <summary>
        /// Create Role By Request ViewModel
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                /** Create IdentiyRole */
                var identityRole = new IdentityRole()
                {
                    Name = model.RoleName
                };

                /** Create Role By IdentiyRole */
                var result = await roleManager.CreateAsync(identityRole);

                /** Check Role Create Success or not */
                if (result.Succeeded)
                {
                    return this.RedirectToAction("ListRoles");
                }

                /** Add Error When Role Creation Fail */
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }

            return View();
        }
        #endregion

        #region GetRoleLists

        /// <summary>
        /// Get Role List From Role
        /// </summary>
        /// <returns></returns>
        public IActionResult ListRoles()
        {
            /** Get All Role Using roleManager */
            var roleLists = roleManager.Roles;
            return this.View(roleLists);
        }
        #endregion

        #region EditRole

        /// <summary>
        /// Edit Role View
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            /** Get User role by request Roleid */
            var role = await roleManager.FindByIdAsync(id);

            /** return to error view when request role not found */
            if(role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id {id} cannot be found";
                return View("NotFound");
            }

            /** create edit role view model */
            var model = new EditRoleViewModel()
            {
                Id = role.Id,
                RoleName = role.Name
            };

            /** find users that have request role */
            var userList = await userManager.Users.ToListAsync();
            foreach (var user in userList)
            {
                if(await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return this.View(model);
        }

        /// <summary>
        /// Edit Role Action
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            /** Get User role by request Roleid */
            var role = await roleManager.FindByIdAsync(model.Id);

            /** return to error view when request role not found */
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;

                /** Update Role Using UpdateAsync */
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                /** add error when update found error */
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return this.View(model);
        }

        #endregion

        #region DeleteRole

        /// <summary>
        ///  Delete user role by request Id
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Policy = "DeleteRolePolicy")]
        public async Task<IActionResult> DeleteRole(string id)
        {
            /** Get role by request Id */
            var role = await roleManager.FindByIdAsync(id);

            /** return to error view when request role not found */
            if (role == null)
            {
                ViewBag.ErrorMessage = $"User with Id {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                try
                {
                    /** Delete role using DeleteAsync */
                    var result = await roleManager.DeleteAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListRoles");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }

                    return View("ListRoles");
                }
                catch(DbUpdateException ex)
                {
                    this.logger.LogError($"Error Deleting role {ex}");
                    ViewBag.ErrorTitle = $"{role.Name} role is in use";
                    ViewBag.ErrorMessage = $"{role.Name} role cannot be deleted as ther are users " +
                        $"in this role. If you want to delete this role, please remove the users from " +
                        $"the role and then try to delete";
                    return this.View("Error");
                }
            }
        }

        #endregion

        #region UserProcess


        #region GetUserLists

        /// <summary>
        /// Get User List From Users
        /// </summary>
        /// <returns></returns>
        public IActionResult ListUsers()
        {
            /** Get All User Using UserManager */
            var userLists = userManager.Users;
            return this.View(userLists);
        }
        #endregion

        #region EditUser

        /// <summary>
        /// Edit User View
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            /** Get User by request id */
            var user = await userManager.FindByIdAsync(id);

            /** return to error view when request user not found */
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id {id} cannot be found";
                return View("NotFound");
            }

            /** Get User claims */
            var userClaims = await userManager.GetClaimsAsync(user);
            /** Get User Roles */
            var userRoles = await userManager.GetRolesAsync(user);

            /** create edit User view model */
            var model = new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                City = user.City,
                Claims = userClaims.Select(c => $"{c.Type} : {c.Value}").ToList(),
                Roles = userRoles.ToList()
            };

            return this.View(model);
        }

        /// <summary>
        ///  Edit User Action
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {
            /** Get User by request id */
            var user = await userManager.FindByIdAsync(model.Id);

            /** return to error view when request user not found */
            if (user == null)
            {
                ViewBag.ErrorMessage = $"Role with Id {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                user.UserName = model.UserName;
                user.City = model.City;
                user.Email = model.Email;

                /** Update User Using UpdateAsync */
                var result = await userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                /** add error when update found error */
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return this.View(model);
        }

        #endregion

Views/Administration/AccessDenied.cshtml
<div class="text-danger text-center">
    <h1 class="text-danger">Access Denied</h1>
    <h6 class="text-danger">
        You do not have permission to view this resource
    </h6>
    <img src="~/images/noaccess.jpg" style="height:300px; width:300px;" />
</div>

Views/Administration/CreateRole.cshtml
@model CreateRoleViewModel

@{
    ViewBag.Title = "Create New Role";
}

<h1> Create New Role </h1>

<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="RoleName"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>

            <button type="submit"
                    class="btn btn-primary"
                    style="width : auto;">
                Create Role
            </button>

        </form>
    </div>
</div>

Views/Administration/EditRole.cshtml
@model EditRoleViewModel

@{
    ViewBag.Title = "Edit Role";
}

<h1> Edit Role </h1> 

<form method="post" class="mt-3">
    <div class="row form-group">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control" />
        </div>
    </div>
    <div class="row form-group">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="row form-group">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="ListRoles" class="btn btn-warning">Cancel</a>
        </div>
     </div>

     <div class="card">
         <div class="card-header">
             <h3>Users in this role</h3>
         </div>
         <div class="card-body">
            @if (Model.Users.Any())
            {
                foreach(var user in Model.Users)
                {
                    <h5 class="card-title"> @user </h5>
                }
            }
            else
            {
                <h5>No User in this role</h5>
            }
        </div>
         <div class="card-footer">
             <a class="btn btn-primary" style="width: auto;"
                 asp-controller="Administration" asp-action="EditUsersInRole"
                 asp-route-id="@Model.Id">
                 Add Or Remove Users
                 </a>
             
         </div>
     </div>

</form>

Views/Administration/EditUser.cshtml
@model EditUserViewModel

@{
    ViewBag.Title = "Edit User";
}

<h1>Edit User</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="UserName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="UserName" class="form-control">
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="City" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="City" class="form-control">
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" asp-action="EditUser" class="btn btn-primary">Update</button>
            <a asp-action="ListUsers" class="btn btn-warning">Cancel</a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>User Roles</h3>
        </div>
        <div class="card-body">
            @if (Model.Roles.Any())
            {
                foreach (var role in Model.Roles)
                {
                    <h5 class="card-title">@role</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="ManageUserRoles" asp-route-userId="@Model.Id" style="width:auto" class="btn btn-primary">
                Manage Roles
            </a>
        </div>
    </div>

    <div class="card mt-3">
        <div class="card-header">
            <h3>User Claims</h3>
        </div>
        <div class="card-body">
            @if (Model.Claims.Any())
            {
                foreach (var claim in Model.Claims)
                {
                    <h5 class="card-title">@claim</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="ManageUserClaims" asp-route-userId="@Model.Id"
               style="width:auto" class="btn btn-primary">
                Manage Claims
            </a>
        </div>
    </div>
</form>

Views/Administration/EditUsersInRole.cshtml
@model List<UserRoleViewModel>

    @{
        var roleId = ViewBag.roleId;
    }

    <form method="post">
        <div class="card">
         <div class="card-header">
             <h2>Add or Remove Users from this role</h2>
         </div>
         <div class="card-body">
            @for(int index = 0; index < Model.Count; index++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[index].UserId">
                    <input type="hidden" asp-for="@Model[index].UserName">
                    <label class="form-check-label">
                        <input asp-for="@Model[index].IsSelected" class="form-check-input">
                        @Model[index].UserName
                    </label>
                </div>
            }
        </div>
         <div class="card-footer">
             <input type="submit" value="Update" class="btn btn-primary" style="width: auto" />
             <a asp-action="EditRole" asp-route-id="@roleId"
                class="btn btn-warning" style="width:auto">Cancel</a>
         </div>
     </div>
    </form>

Views/Administration/ListRoles.cshtml
@model IEnumerable<IdentityRole>
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationService

    @{
    ViewBag.Title = "Role Lists";
}

@if (Model.Any())
{
    <a class="btn btn-primary mt-2" style="width : auto;"
   asp-controller="administration" asp-action="createRole">
        Create Role
    </a>
    foreach (var role in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Role Id : @role.Id
            </div>
            <div class="card-body">
                @role.Name
            </div>
            <div class="card-footer">
        
                <form asp-action="DeleteRole" asp-route-id="@role.Id" method="post">
                    @if((await authorizationService.AuthorizeAsync(User, "EditRolePolicy")).Succeeded)
                    {
                        <a class="btn btn-primary"
                            asp-action="EditRole"
                            asp-controller="Administration"
                            asp-route-id="@role.Id">
                            Edit
                        </a>
                    }

                    <span id="confirmDeleteSpan_@role.Id" style="display:none;">
                        <span>Are You Sure You Want To Delete?</span>
                        <button type="submit" class="btn btn-danger">Yes</button>
                        <a href="#" class="btn btn-warning"
                            onclick="confirmDelete('@role.Id', false)">
                            No
                        </a>
                    </span>

                    <span id="deleteSpan_@role.Id">
                        <a href="#" class="btn btn-danger"
                            onclick="confirmDelete('@role.Id', true)">
                        Delete
                    </a>
                    </span>
                </form>
            </div>
        </div>
    }
}
else
{
    <div class="card mt-2">
        <div class="card-header">
            No roles created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create a new role
            </h5>
            <a class="btn btn-primary" style="width : auto;"
           asp-controller="administration" asp-action="createRole">
                Create Role
            </a>
        </div>
    </div>
}

@section Scripts{
    <script src="~/js/site.js"></script>
}

Views/Administration/ListUsers.cshtml
@model IEnumerable<ApplicationUser>

    @{
    ViewBag.Title = "User Lists";
}

@if (Model.Any())
{
    <a class="btn btn-primary mt-2" style="width : auto;"
   asp-controller="account" asp-action="register">
        Create New User
    </a>
    foreach (var user in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                User Id : @user.Id
            </div>
            <div class="card-body">
                @user.UserName
            </div>
            <div class="card-footer">
                <form asp-action="DeleteUser" asp-route-id="@user.Id" method="post">
                    <a class="btn btn-primary"
                       asp-action="EditUser"
                       asp-controller="Administration"
                       asp-route-id="@user.Id">
                        Edit
                    </a>

                    <span id="confirmDeleteSpan_@user.Id" style="display:none;">
                        <span>Are You Sure You Want To Delete?</span>
                        <button type="submit" class="btn btn-danger">Yes</button>
                        <a href="#" class="btn btn-warning"
                            onclick="confirmDelete('@user.Id', false)">
                            No
                        </a>
                    </span>

                    <span id="deleteSpan_@user.Id">
                        <a href="#" class="btn btn-danger"
                            onclick="confirmDelete('@user.Id', true)">
                        Delete
                    </a>
                    </span>
                </form>
            </div>
        </div>
    }
}
else
{
    <div class="card mt-2">
        <div class="card-header">
            No Users created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create a new User
            </h5>
            <a class="btn btn-primary" style="width: auto;"
           asp-controller="Account" asp-action="Register">
                Add New User
            </a>
        </div>
    </div>
}

@section Scripts{
    <script src="~/js/site.js"></script>
}

Views/Administration/ManageUserClaims.cshtml
@model UserClaimsViewModel

@{
    ViewBag.Title = "User Claims";
}

<form method="post">
    <div class="card mt-3">
        <div class="card-header">
            <h3>Manage User Claims</h3>
        </div>
        <div class="card-body">
            @for(int index = 0; index < Model.Claims.Count; index++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model.Claims[index].ClaimType">
                    <label class="form-check-label">
                        <input asp-for="@Model.Claims[index].IsSelected" class="form-check-input">
                        @Model.Claims[index].ClaimType
                    </label>
                </div>
            }

            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary" style="width: auto">
                Update
            </button>
            <a asp-action="EditUser" asp-route-id="@Model.UserId"
               style="width:auto" class="btn btn-warning">
                Cancel
            </a>
        </div>
    </div>
</form>

Views/Administration/ManageUserRoles.cshtml
@model List<UserRolesViewModel>

    @{
    ViewBag.Title = "User Roles";
    var userId = ViewBag.userId;
}

<form method="post">
    <div class="card mt-3">
        <div class="card-header">
            <h3>Manage user Roles</h3>
        </div>
        <div class="card-body">
            @for(int index = 0; index < Model.Count; index++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[index].RoleId">
                    <input type="hidden" asp-for="@Model[index].RoleName">
                    <label class="form-check-label">
                        <input asp-for="@Model[index].IsSelected" class="form-check-input">
                        @Model[index].RoleName
                    </label>
                </div>
            }

            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary" style="width: auto">
                Update
            </button>
            <a asp-action="EditUser" asp-route-id="@userId"
               style="width:auto" class="btn btn-warning">
                Cancel
            </a>
        </div>
    </div>
</form>